server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/productdb
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.MySQLDialect
  application:
    name: ProductService
  config:
    import: configserver:http://localhost:9296